source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!


target 'vividFacesDemo iOS' do
    pod 'TensorFlow-experimental'
    pod 'Alamofire', '~> 4.7'
    pod 'QMUIKit'
    pod 'KeychainSwift', '~> 11.0'
    pod 'SwiftyJSON'
    pod 'ZIPFoundation'
    pod 'M13ProgressSuite'
end
